import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  fr: {
    nav_home: 'Accueil',
    nav_courses: 'Formations',
    nav_about: 'À propos',
    nav_gallery: 'Galerie',
    nav_testimonials: 'Témoignages',
    nav_contact: 'Contact',
    nav_login: 'Connexion',
    nav_register: "S'inscrire",
    nav_my_space: 'Mon Espace',
    nav_my_enrollments: 'Mes Inscriptions',
    nav_my_payments: 'Mes paiements',
    nav_my_receipts: 'Mes reçus',
    nav_settings: 'Paramètres',
    nav_logout: 'Déconnexion',
    nav_admin: 'Espace Admin',
    nav_formateur: 'Espace Formateur',
    nav_annonceur: 'Espace Annonceur',
    
    hero_title: 'Former Aujourd\'hui',
    hero_title_accent: 'Les Talents Numériques',
    hero_title_end: 'de Demain',
    hero_desc: 'Nous accompagnons les enfants et les jeunes de 8 à 18 ans dans l\'acquisition des compétences informatiques essentielles.',
    hero_cta: "S'inscrire Maintenant",
    hero_card_title: 'Inscriptions ouvertes 2026',
    hero_card_subtitle: 'Offrez à votre enfant les compétences du futur !',
    hero_card_btn: 'Je réserve ma place',
    hero_ai_title: "Découvrez l'Intelligence Artificielle pour les jeunes",
    hero_ai_subtitle: 'Comprendre, créer, innover avec les technologies de demain.',
    hero_ai_btn: 'En savoir plus',

    about_eyebrow: 'Qui sommes-nous ?',
    about_title: 'L\'informatique à la portée de vos enfants',
    about_desc1: 'Donnez à vos enfants les clés pour comprendre et créer la technologie de demain, grâce à un apprentissage 100% pratique et adapté à leur âge.',
    about_desc2: 'Notre mission est de préparer la prochaine génération aux défis du monde numérique en leur offrant des compétences solides en bureautique, sécurité internet, et intelligence artificielle, dans un cadre ludique et stimulant.',
    about_feat1: 'Excellence pédagogique',
    about_feat2: 'Environnement sécurisé',
    about_years: 'Années d\'expérience',

    courses_eyebrow: 'Nos Formations',
    courses_title: 'Formations en vedette',
    courses_subtitle: 'Découvrez nos programmes les plus populaires conçus pour vos enfants.',
    courses_more: 'Voir toutes les formations',
    courses_remaining: 'places restantes',
    courses_full: 'Complet',
    courses_enroll: "S'inscrire",
    courses_free: 'Gratuit',

    why_eyebrow: 'Nos Atouts',
    why_title: 'Pourquoi nous choisir ?',
    why_subtitle: 'L\'environnement idéal pour le développement des compétences de vos enfants.',

    why_feat1_title: 'Formateurs qualifiés',
    why_feat1_desc: 'Des professionnels passionnés par la transmission des connaissances.',
    why_feat2_title: 'Programmes adaptés',
    why_feat2_desc: 'Des contenus conçus spécifiquement pour les enfants et adolescents.',
    why_feat3_title: 'Apprentissage pratique',
    why_feat3_desc: 'Plus de pratique que de théorie pour des compétences concrètes.',
    why_feat4_title: 'Certifications',
    why_feat4_desc: 'Des attestations de participation et de fin de formation sont délivrées.',
    why_feat5_title: 'Suivi individuel',
    why_feat5_desc: 'Chaque apprenant est accompagné tout au long de son parcours.',
    why_feat6_title: 'Horaires flexibles',
    why_feat6_desc: 'Formations disponibles en présentiel, à domicile ou en ligne selon vos besoins.',

    program_office: 'Bureautique',
    program_safety: 'Internet & Sécurité',
    program_prog: 'Programmation',
    program_ai: 'Intelligence Artificielle',
    program_coaching: 'Accompagnement personnalisé',

    stats_title: 'Novatech Vision en Chiffres',
    stats_subtitle: 'Notre impact et notre engagement envers l\'excellence.',
    stats_students: 'Enfants formés',
    stats_courses: 'Formations',
    stats_satisfaction: 'Parents satisfaits',
    stats_experts: 'Formateurs experts',

    contact_eyebrow: 'Restons connectés',
    contact_title: 'Rejoignez la communauté',
    contact_desc: 'Suivez nos actualités, nos événements et interagissez avec nous sur les réseaux sociaux. Nous sommes disponibles pour répondre à toutes vos questions.',
    contact_form_title: 'Formulaire de contact rapide',
    contact_form_name: 'Votre nom complet',
    contact_form_email: 'Votre adresse email',
    contact_form_subject: 'Sujet',
    contact_form_body: 'Votre message...',
    contact_form_sending: 'Envoi en cours...',
    contact_form_sent: 'Message envoyé !',
    contact_form_submit: 'Envoyer le message',

    footer_desc: 'Spécialisé dans l\'éducation numérique et l\'informatique pour enfants et adolescents de 8 à 18 ans.',
    footer_quick_links: 'Liens rapides',
    footer_rights: 'Tous droits réservés.',
    footer_privacy: 'Politique de confidentialité',
    footer_terms: "Conditions d'utilisation",

    // Common/Layout
    loading: 'Chargement...',
    back: 'Retour',
    cancel: 'Annuler',
    save: 'Enregistrer',
    edit: 'Modifier',
    delete: 'Supprimer',
    submit: 'Soumettre',
    actions: 'Actions',
    status: 'Statut',
    details: 'Détails',

    // Inscription Form
    ins_title: "Formulaire d'Inscription",
    ins_step1: '1. Informations',
    ins_step2: '2. Paiement',
    ins_choice: 'Choix de la Formation',
    ins_select_course: 'Sélectionnez une formation *',
    ins_choose_opt: '-- Choisir --',
    ins_child_info: "Informations de l'enfant (Apprenant)",
    ins_child_firstname: 'Prénom *',
    ins_child_lastname: 'Nom *',
    ins_child_age: "Âge de l'enfant *",
    ins_parent_info: 'Informations du Parent / Tuteur',
    ins_parent_fullname: 'Nom complet du parent *',
    ins_parent_phone: 'Téléphone *',
    ins_parent_email: 'Email *',
    ins_address: 'Adresse physique (Ville, Quartier) *',
    ins_payment_type: 'Type de Paiement',
    ins_pay_complet: "Paiement complet à l'inscription",
    ins_pay_mensuel: 'Paiement en 2 fois (50% maintenant)',
    ins_next_step: 'Étape Suivante',
    ins_summary: 'Récapitulatif de votre inscription',
    ins_course: 'Formation :',
    ins_student: 'Apprenant :',
    ins_parent: 'Parent :',
    ins_total_to_pay: 'Total à payer :',
    ins_full_title: 'Formation complète',
    ins_full_desc: "Aucun paiement n'est requis pour le moment. Vous allez être placé(e) sur liste d'attente.",
    ins_confirm_waitlist: "Confirmer l'inscription sur liste d'attente",
    ins_proceed_payment: 'Procéder au paiement',
    ins_payment_desc: 'Cliquez sur le bouton ci-dessous pour régler par Mobile Money ou Carte Bancaire via notre partenaire sécurisé.',
    ins_duration: 'Durée',
    ins_audience: 'Public',
    ins_format: 'Format',
    ins_online: 'En ligne 💻',
    ins_in_person: 'Présentiel 🏫',
    ins_waitlist_warning: "⚠ COMPLET — Liste d'attente",
    ins_total_price: 'Prix total',
    ins_secure_payment: 'Paiement Sécurisé',
    ins_secure_payment_desc: 'Vos données sont chiffrées de bout en bout',
    ins_privacy: 'Confidentialité',
    ins_privacy_desc: 'Vos informations ne sont jamais partagées',

    // InscriptionFormation Catalog
    cat_title: 'Catalogue de Formations',
    cat_subtitle: 'Choisissez la formation idéale pour initier votre enfant au numérique dans un cadre sécurisé et encadré par des professionnels.',
    cat_search_placeholder: 'Rechercher une formation...',
    cat_filters: 'Filtres',
    cat_category: 'Catégorie',
    cat_category_all: 'Toutes',
    cat_price_min: 'Prix min (FCFA)',
    cat_price_max: 'Prix max (FCFA)',
    cat_sort_by: 'Trier par',
    cat_sort_recent: 'Plus récents',
    cat_sort_price_asc: 'Prix croissant',
    cat_sort_price_desc: 'Prix décroissant',
    cat_sort_alpha: 'Ordre alphabétique',
    cat_no_course: 'Aucune formation trouvée. Essayez de modifier vos filtres.',
    cat_spots_left: 'places restantes',
    cat_spots_only: 'Plus que {spots} places !',
    cat_spots: 'places',
    cat_details: 'Détails',
    cat_enroll: "S'inscrire",
    cat_waitlist: "Liste d'attente",
    cat_secure_banner_title: 'Paiement 100% sécurisé via FedaPay',
    cat_secure_banner_desc: 'Vos transactions sont cryptées et protégées. Nous ne conservons aucune donnée bancaire.',

    // FormationDetails
    fd_back: 'Retour aux formations',
    fd_about: 'À propos de cette formation',
    fd_default_desc: 'Cette formation est spécialement conçue pour vous permettre de maîtriser de nouvelles compétences pratiques, étape par étape.',
    fd_practical: 'Détails pratiques',
    fd_level: 'Niveau :',
    fd_all_levels: 'Tous niveaux',
    fd_format: 'Format :',
    fd_pace: 'Rythme :',
    fd_sessions_week: 'séances par semaine',
    fd_curriculum: 'Programme de la formation',
    fd_module: 'Module',
    fd_chapters: 'chapitres',
    fd_lessons: 'leçon(s) au programme',
    fd_spots_left: 'Il reste {spots} place(s) disponible(s)',
    fd_enroll_now: "S'inscrire maintenant",
    fd_secure_pay: 'Paiement 100% sécurisé',
    fd_secure_desc: 'Transaction cryptée via FedaPay',

    // ApprenantDashboard
    dash_welcome: 'Bonjour,',
    dash_courses_in_progress: 'formation(s) en cours',
    dash_payments_done: 'paiement(s) effectué(s)',
    dash_resume_courses: 'Reprendre mes cours',
    dash_enrolled_courses: 'Formations inscrites',
    dash_global_progress: 'Progression globale',
    dash_last_activity: 'Dernière activité',
    dash_last_activity_today: "Aujourd'hui",
    dash_notifications: '🔔 Notifications importantes',
    dash_no_notifications: 'Aucune notification pour le moment.',
    dash_join_live_notification: "N'oubliez pas de rejoindre votre prochain cours Live.",
    dash_my_courses: 'Mes Formations',
    dash_no_courses: 'Aucune formation',
    dash_no_courses_desc: "Vous n'êtes inscrit à aucune formation pour l'instant.",
    dash_student: 'Élève :',
    dash_enrolled_on: 'Inscrit le',
    dash_course_progress: 'Progression dans le cours',
    dash_view_syllabus: 'Voir le programme',
    dash_join_live: 'Rejoindre le Live',
    dash_cancel_enrollment: 'Annuler inscription',
    dash_pedagogical_resources: 'Ressources Pédagogiques',
    dash_no_resources: 'Inscrivez-vous à une formation pour voir les ressources.',
    dash_course_support: 'Supports de cours numériques disponibles',
    dash_open: 'Ouvrir',
    dash_watch: 'Visionner',
    dash_payment_history: 'Historique des Paiements',
    dash_date: 'Date',
    dash_type: 'Type',
    dash_installments: 'Mensualités',
    dash_amount_paid: 'Montant payé',
    dash_status: 'Statut',
    dash_actions: 'Actions',
    dash_status_incomplete: 'Incomplet',
    dash_status_paid: 'Payé',
    dash_pay_installment: 'Payer échéance',
    dash_receipt: 'Reçu',
    dash_no_payments: 'Aucun paiement trouvé.',
    dash_installment_modal_title: 'Régler la mensualité suivante',
    dash_installment_modal_desc: 'Vous vous apprêtez à payer la mensualité suivante.',
    dash_installment_amount: 'Montant de la mensualité :',
    dash_profile_info: '👤 Informations du Profil',
    dash_personal_info: 'Informations personnelles',
    dash_password: '🔒 Mot de passe',
    dash_change_password: 'Modifier le mot de passe',
    dash_current_password: 'Mot de passe actuel',
    dash_new_password: 'Nouveau mot de passe',
    dash_confirm_password: 'Confirmer le mot de passe',
    dash_update_btn: 'Mettre à jour',
    dash_save_changes: 'Enregistrer les modifications',
    dash_become_trainer: 'Devenir Formateur',
    dash_become_trainer_desc: "Rejoignez l'équipe pédagogique de Novatech Vision et partagez votre passion avec la nouvelle génération !",
    dash_apply_specialty: 'Spécialité *',
    dash_apply_bio: 'Biographie *',
    dash_apply_photo: "Photo d'identité (URL) *",
    dash_apply_submit: 'Envoyer ma candidature',
    dash_modify_photo: 'Modifier la photo',
    dash_delete_photo: 'Supprimer',
    dash_student_role: 'Apprenant',
    dash_firstname: 'Prénom',
    dash_lastname: 'Nom',
    dash_email: 'Email',
    dash_phone: 'Téléphone apprenant',
    dash_parent_section: 'Parent / Tuteur',
    dash_parent_fullname: 'Nom complet du parent',
    dash_parent_phone: 'Téléphone du parent',
    dash_save_profile: 'Enregistrer les modifications',
    dash_password_section: '🔒 Mot de passe',
    dash_current_pwd: 'Mot de passe actuel',
    dash_new_pwd: 'Nouveau mot de passe',
    dash_confirm_pwd: 'Confirmer le mot de passe',
    dash_update_pwd: 'Mettre à jour',
    dash_alert_profile_success: 'Profil mis à jour',
    dash_alert_server_error: 'Erreur serveur',
    dash_alert_pwd_mismatch: 'Les mots de passe ne correspondent pas.',
    dash_alert_pwd_success: 'Mot de passe mis à jour',
    dash_alert_error: 'Erreur',
    dash_alert_avatar_upload_error: "Erreur lors de l'upload",
    dash_alert_avatar_delete_confirm: 'Supprimer la photo de profil ?',
    dash_apply_pending_title: "Candidature en cours d'examen",
    dash_apply_pending_desc: "Votre candidature pour devenir formateur est actuellement en cours de révision par notre équipe. Nous vous contacterons très prochainement.",
    dash_apply_title: 'Devenir Formateur',
    dash_apply_desc: "Rejoignez l'équipe pédagogique de Novatech Vision et partagez votre passion avec la nouvelle génération !",
    dash_apply_rejected: "Votre précédente candidature n'a pas été retenue. Vous pouvez soumettre une nouvelle demande.",
    dash_apply_specialty_placeholder: 'Ex: Développement Web, Intelligence Artificielle...',
    dash_apply_bio_placeholder: 'Présentez-vous brièvement et expliquez pourquoi vous souhaitez devenir formateur...',
    dash_apply_photo_opt: 'Lien vers photo de profil / portfolio (Optionnel)',
    dash_apply_submit_btn: 'Soumettre ma candidature',
    dash_apply_error: "Erreur lors de l'envoi de la candidature",
  },
  en: {
    nav_home: 'Home',
    nav_courses: 'Courses',
    nav_about: 'About Us',
    nav_gallery: 'Gallery',
    nav_testimonials: 'Testimonials',
    nav_contact: 'Contact',
    nav_login: 'Login',
    nav_register: 'Register',
    nav_my_space: 'My Space',
    nav_my_enrollments: 'My Enrollments',
    nav_my_payments: 'My Payments',
    nav_my_receipts: 'My Receipts',
    nav_settings: 'Settings',
    nav_logout: 'Logout',
    nav_admin: 'Admin Space',
    nav_formateur: 'Trainer Space',
    nav_annonceur: 'Advertiser Space',
    
    hero_title: 'Training Today',
    hero_title_accent: 'The Digital Talents',
    hero_title_end: 'of Tomorrow',
    hero_desc: 'We support children and teenagers from 8 to 18 years old in acquiring essential computer skills.',
    hero_cta: 'Register Now',
    hero_card_title: 'Registration Open 2026',
    hero_card_subtitle: 'Give your child the skills of the future!',
    hero_card_btn: 'Book my spot',
    hero_ai_title: 'Discover Artificial Intelligence for youth',
    hero_ai_subtitle: 'Understand, create, and innovate with tomorrow\'s technologies.',
    hero_ai_btn: 'Learn more',

    about_eyebrow: 'Who are we?',
    about_title: 'IT training at your child\'s reach',
    about_desc1: 'Give your children the keys to understand and create the technology of tomorrow, with 100% practical learning adapted to their age.',
    about_desc2: 'Our mission is to prepare the next generation for the challenges of the digital world by providing solid skills in office tools, internet safety, and AI, within a fun and stimulating environment.',
    about_feat1: 'Pedagogical excellence',
    about_feat2: 'Safe environment',
    about_years: 'Years of experience',

    courses_eyebrow: 'Our Courses',
    courses_title: 'Featured Courses',
    courses_subtitle: 'Discover our most popular programs designed for your children.',
    courses_more: 'View all courses',
    courses_remaining: 'spots remaining',
    courses_full: 'Full',
    courses_enroll: 'Enroll',
    courses_free: 'Free',

    why_eyebrow: 'Our Strengths',
    why_title: 'Why choose us?',
    why_subtitle: 'The ideal environment for developing your children\'s skills.',

    why_feat1_title: 'Qualified trainers',
    why_feat1_desc: 'Passionate professionals dedicated to sharing knowledge.',
    why_feat2_title: 'Tailored programs',
    why_feat2_desc: 'Content specifically designed for kids and teenagers.',
    why_feat3_title: 'Hands-on learning',
    why_feat3_desc: 'More practice than theory for concrete skill building.',
    why_feat4_title: 'Certifications',
    why_feat4_desc: 'Participation and completion certificates are awarded.',
    why_feat5_title: 'Individual tracking',
    why_feat5_desc: 'Each student is supported throughout their journey.',
    why_feat6_title: 'Flexible hours',
    why_feat6_desc: 'Courses available in-person, at-home, or online according to your needs.',

    program_office: 'Office Tools',
    program_safety: 'Internet & Safety',
    program_prog: 'Programming',
    program_ai: 'Artificial Intelligence',
    program_coaching: 'Personalized Coaching',

    stats_title: 'Novatech Vision in Figures',
    stats_subtitle: 'Our impact and our commitment to excellence.',
    stats_students: 'Children trained',
    stats_courses: 'Courses',
    stats_satisfaction: 'Satisfied parents',
    stats_experts: 'Expert trainers',

    contact_eyebrow: 'Stay connected',
    contact_title: 'Join the community',
    contact_desc: 'Follow our news, events and interact with us on social media. We are here to answer all your questions.',
    contact_form_title: 'Quick contact form',
    contact_form_name: 'Your full name',
    contact_form_email: 'Your email address',
    contact_form_subject: 'Subject',
    contact_form_body: 'Your message...',
    contact_form_sending: 'Sending...',
    contact_form_sent: 'Message sent!',
    contact_form_submit: 'Send message',

    footer_desc: 'Specialized in digital education and computer training for kids and teens aged 8 to 18.',
    footer_quick_links: 'Quick Links',
    footer_rights: 'All rights reserved.',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',

    // Common/Layout
    loading: 'Loading...',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    submit: 'Submit',
    actions: 'Actions',
    status: 'Status',
    details: 'Details',

    // Inscription Form
    ins_title: 'Registration Form',
    ins_step1: '1. Information',
    ins_step2: '2. Payment',
    ins_choice: 'Course Selection',
    ins_select_course: 'Select a course *',
    ins_choose_opt: '-- Choose --',
    ins_child_info: 'Child Details (Student)',
    ins_child_firstname: 'First Name *',
    ins_child_lastname: 'Last Name *',
    ins_child_age: "Child's Age *",
    ins_parent_info: 'Parent / Guardian Information',
    ins_parent_fullname: "Parent's Full Name *",
    ins_parent_phone: 'Phone *',
    ins_parent_email: 'Email *',
    ins_address: 'Physical Address (City, District) *',
    ins_payment_type: 'Payment Option',
    ins_pay_complet: 'Full payment upon registration',
    ins_pay_mensuel: 'Pay in 2 installments (50% now)',
    ins_next_step: 'Next Step',
    ins_summary: 'Summary of your registration',
    ins_course: 'Course:',
    ins_student: 'Student:',
    ins_parent: 'Parent:',
    ins_total_to_pay: 'Total to pay:',
    ins_full_title: 'Course Full',
    ins_full_desc: 'No payment is required at this time. You will be placed on the waitlist.',
    ins_confirm_waitlist: 'Confirm waitlist registration',
    ins_proceed_payment: 'Proceed to payment',
    ins_payment_desc: 'Click the button below to pay via Mobile Money or Credit Card through our secure partner.',
    ins_duration: 'Duration',
    ins_audience: 'Audience',
    ins_format: 'Format',
    ins_online: 'Online 💻',
    ins_in_person: 'In-person 🏫',
    ins_waitlist_warning: '⚠ FULL — Waitlist',
    ins_total_price: 'Total Price',
    ins_secure_payment: 'Secure Payment',
    ins_secure_payment_desc: 'Your data is encrypted end-to-end',
    ins_privacy: 'Privacy',
    ins_privacy_desc: 'Your information is never shared',

    // InscriptionFormation Catalog
    cat_title: 'Course Catalog',
    cat_subtitle: 'Choose the ideal course to introduce your child to the digital world in a safe environment supervised by professionals.',
    cat_search_placeholder: 'Search for a course...',
    cat_filters: 'Filters',
    cat_category: 'Category',
    cat_category_all: 'All',
    cat_price_min: 'Min Price (FCFA)',
    cat_price_max: 'Max Price (FCFA)',
    cat_sort_by: 'Sort by',
    cat_sort_recent: 'Most recent',
    cat_sort_price_asc: 'Price low to high',
    cat_sort_price_desc: 'Price high to low',
    cat_sort_alpha: 'Alphabetical order',
    cat_no_course: 'No course found. Try modifying your filters.',
    cat_spots_left: 'spots remaining',
    cat_spots_only: 'Only {spots} spots left!',
    cat_spots: 'spots',
    cat_details: 'Details',
    cat_enroll: 'Enroll',
    cat_waitlist: 'Waitlist',
    cat_secure_banner_title: '100% Secure Payment via FedaPay',
    cat_secure_banner_desc: 'Your transactions are encrypted and protected. We do not store any banking data.',

    // FormationDetails
    fd_back: 'Back to courses',
    fd_about: 'About this course',
    fd_default_desc: 'This course is specially designed to allow you to master new practical skills, step by step.',
    fd_practical: 'Practical details',
    fd_level: 'Level :',
    fd_all_levels: 'All levels',
    fd_format: 'Format :',
    fd_pace: 'Pace :',
    fd_sessions_week: 'sessions per week',
    fd_curriculum: 'Course curriculum',
    fd_module: 'Module',
    fd_chapters: 'chapters',
    fd_lessons: 'lesson(s) in curriculum',
    fd_spots_left: '{spots} spot(s) remaining',
    fd_enroll_now: 'Enroll now',
    fd_secure_pay: '100% secure payment',
    fd_secure_desc: 'Encrypted transaction via FedaPay',

    // ApprenantDashboard
    dash_welcome: 'Hello,',
    dash_courses_in_progress: 'course(s) in progress',
    dash_payments_done: 'payment(s) made',
    dash_resume_courses: 'Resume my courses',
    dash_enrolled_courses: 'Enrolled courses',
    dash_global_progress: 'Overall progress',
    dash_last_activity: 'Last activity',
    dash_last_activity_today: 'Today',
    dash_notifications: '🔔 Important notifications',
    dash_no_notifications: 'No notifications at the moment.',
    dash_join_live_notification: "Don't forget to join your next Live course.",
    dash_my_courses: 'My Courses',
    dash_no_courses: 'No courses',
    dash_no_courses_desc: 'You are not enrolled in any courses at the moment.',
    dash_student: 'Student:',
    dash_enrolled_on: 'Enrolled on',
    dash_course_progress: 'Course progress',
    dash_view_syllabus: 'View syllabus',
    dash_join_live: 'Join Live',
    dash_cancel_enrollment: 'Cancel enrollment',
    dash_pedagogical_resources: 'Pedagogical Resources',
    dash_no_resources: 'Enroll in a course to view resources.',
    dash_course_support: 'Digital course materials available',
    dash_open: 'Open',
    dash_watch: 'Watch',
    dash_payment_history: 'Payment History',
    dash_date: 'Date',
    dash_type: 'Type',
    dash_installments: 'Installments',
    dash_amount_paid: 'Amount paid',
    dash_status: 'Status',
    dash_actions: 'Actions',
    dash_status_incomplete: 'Incomplete',
    dash_status_paid: 'Paid',
    dash_pay_installment: 'Pay installment',
    dash_receipt: 'Receipt',
    dash_no_payments: 'No payments found.',
    dash_installment_modal_title: 'Pay Next Installment',
    dash_installment_modal_desc: 'You are about to pay the next installment.',
    dash_installment_amount: 'Installment amount:',
    dash_profile_info: '👤 Profile Information',
    dash_personal_info: 'Personal information',
    dash_password: '🔒 Password',
    dash_change_password: 'Change password',
    dash_current_password: 'Current password',
    dash_new_password: 'New password',
    dash_confirm_password: 'Confirm password',
    dash_update_btn: 'Update',
    dash_save_changes: 'Save changes',
    dash_become_trainer: 'Become a Trainer',
    dash_become_trainer_desc: 'Join the Novatech Vision pedagogical team and share your passion with the next generation!',
    dash_apply_specialty: 'Specialty *',
    dash_apply_bio: 'Biography *',
    dash_apply_photo: 'ID Photo (URL) *',
    dash_apply_submit: 'Submit application',
    dash_profile_info: '👤 Profile Information',
    dash_modify_photo: 'Change photo',
    dash_delete_photo: 'Delete',
    dash_student_role: 'Student',
    dash_firstname: 'First Name',
    dash_lastname: 'Last Name',
    dash_email: 'Email',
    dash_phone: 'Student phone',
    dash_parent_section: 'Parent / Guardian',
    dash_parent_fullname: "Parent's full name",
    dash_parent_phone: "Parent's phone",
    dash_save_profile: 'Save changes',
    dash_password_section: '🔒 Password',
    dash_current_pwd: 'Current password',
    dash_new_pwd: 'New password',
    dash_confirm_pwd: 'Confirm password',
    dash_update_pwd: 'Update',
    dash_alert_profile_success: 'Profile updated',
    dash_alert_server_error: 'Server error',
    dash_alert_pwd_mismatch: 'Passwords do not match.',
    dash_alert_pwd_success: 'Password updated',
    dash_alert_error: 'Error',
    dash_alert_avatar_upload_error: 'Error uploading avatar',
    dash_alert_avatar_delete_confirm: 'Delete profile picture?',
    dash_apply_pending_title: 'Application under review',
    dash_apply_pending_desc: 'Your application to become a trainer is currently under review by our team. We will contact you very soon.',
    dash_apply_title: 'Become a Trainer',
    dash_apply_desc: 'Join the Novatech Vision pedagogical team and share your passion with the next generation!',
    dash_apply_rejected: 'Your previous application was not accepted. You can submit a new request.',
    dash_apply_specialty_placeholder: 'E.g., Web Development, Artificial Intelligence...',
    dash_apply_bio_placeholder: 'Introduce yourself briefly and explain why you want to become a trainer...',
    dash_apply_photo_opt: 'Link to profile picture / portfolio (Optional)',
    dash_apply_submit_btn: 'Submit my application',
    dash_apply_error: 'Error submitting application',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('nv_lang') || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('nv_lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'fr' ? 'en' : 'fr'));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
